spring:
  profiles:
    active: zmq
  application:
    name: cloud-web
server:
  port: 8081

#\u670D\u52A1\u6CE8\u518C\u7684Eureka Server\u5730\u5740
eureka:
#  datacenter: cloud
  environment: ${spring.profiles.active}
  instance:
    hostname: 192.168.0.176
    prefer-ip-address: true
    #\u81EA\u5B9A\u4E49\u5E94\u7528\u5B9E\u4F8Bid
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
    #\u5065\u5EB7\u68C0\u67E5
    healthcheck:
      enabled: true
management:
  endpoints:
    web:
      expose: "*"
