spring:
  profiles:
    active: zmq
  application:
    name: cloud-commons
server:
  port: 8080

#服务注册的Eureka Server地址
eureka:
#  datacenter: cloud
  environment: ${spring.profiles.active}
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    #自定义应用实例id
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
    #健康检查
    healthcheck:
      enabled: true
