server:
  port: 9000

spring:
  profiles:
    active: zmq
  application:
    name: eureka-1
#    active: @spring.cloud.env@

eureka:
#  datacenter: cloud
  environment: ${spring.profiles.active}
  instance:
    hostname: 192.168.0.138
#    使用ip地址定义注册中心地址
    prefer-ip-address: true
  client:
#  表示应用是否是想注册中心注册自己(配置高可用的时候需要设置为true.)
    registerWithEureka: false
#    是否去检索服务
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.0.176:${server.port}/eureka/
